// Parses the markdown-ish text generated by the diet AI + DIET_TEMPLATE
// into structured sections so DietViewer can render them visually.
//
// The text typically contains, in order:
//   # PROGRAMA NUTRICIONAL
//   ## TUS MACROS DIARIOS  (we ignore — DietViewer reads numeric columns)
//   ## DISTRIBUCIÓN DE COMIDAS
//     🌅 DESAYUNO (08:00):
//     - 120g claras de huevo
//     - ...
//     💡 Nota: ...
//     ☀️ MEDIA MAÑANA (...): ...
//     ...
//     🎯 RECOMENDACIONES PERSONALIZADAS
//     • Cardio: ...
//     • Hidratación: ...
//   ## REGLAS GENERALES PARA TODAS LAS COMIDAS
//   ## SUPLEMENTACIÓN
//   ## OBSERVACIONES GENERALES
//   ## FLUIDOS
//   ⚠️ DESCARGO DE RESPONSABILIDAD: ...

const MEAL_EMOJI_RE = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u
// Lines that look like a meal header: "<emoji> NAME (HH:MM):".
// Emoji can be a single Extended_Pictographic codepoint optionally followed by
// the U+FE0F variation selector and other ZWJ-joined codepoints.
const MEAL_HEADER_RE = new RegExp(
  '^([\\p{Extended_Pictographic}](?:\\uFE0F|\\u200D[\\p{Extended_Pictographic}])*)\\s*([^()\\n]+?)\\s*\\((\\d{1,2}:\\d{2})\\)\\s*:?\\s*$',
  'u'
)
const NOTE_RE = /^💡\s*Nota[:\-]?\s*(.+)$/i
const RECOMMENDATIONS_HEADER_RE = /^🎯\s*RECOMENDACIONES\s+PERSONALIZADAS\s*$/i
const SECTION_HEADER_RE = /^##\s+(.+?)\s*$/

const TEMPLATE_SECTION_KEYS = {
  'reglas generales para todas las comidas': 'generalRules',
  'suplementación': 'supplementation',
  'suplementacion': 'supplementation',
  'observaciones generales': 'observations',
  'fluidos': 'fluids',
  'tus macros diarios': 'macros',
  'distribución de comidas': 'meals',
  'distribucion de comidas': 'meals'
}

const norm = s => (s || '').trim().toLowerCase()

function isBulletLine(line) {
  return /^\s*[-•]\s+/.test(line)
}

function stripBullet(line) {
  return line.replace(/^\s*[-•]\s+/, '').trim()
}

function isDisclaimerLine(line) {
  return /^⚠️/.test(line) || /DESCARGO DE RESPONSABILIDAD/i.test(line)
}

export function parseDietContent(content) {
  const empty = {
    meals: [],
    recommendations: [],
    sections: {
      generalRules: '',
      supplementation: '',
      observations: '',
      fluids: ''
    },
    disclaimer: '',
    rawFallback: false
  }
  if (!content || typeof content !== 'string') {
    return { ...empty, rawFallback: true }
  }

  const lines = content.split(/\r?\n/)
  const result = {
    meals: [],
    recommendations: [],
    sections: {
      generalRules: '',
      supplementation: '',
      observations: '',
      fluids: ''
    },
    disclaimer: '',
    rawFallback: false
  }

  let mode = 'top' // 'top' | 'meals' | 'recommendations' | 'template' | 'disclaimer'
  let currentMeal = null
  let currentTemplateKey = null
  let templateBuffer = []
  let disclaimerBuffer = []

  const flushMeal = () => {
    if (currentMeal) result.meals.push(currentMeal)
    currentMeal = null
  }

  const flushTemplate = () => {
    if (currentTemplateKey && result.sections[currentTemplateKey] !== undefined) {
      result.sections[currentTemplateKey] = templateBuffer
        .join('\n')
        .replace(/\n*-{3,}\s*$/m, '')
        .trim()
    }
    currentTemplateKey = null
    templateBuffer = []
  }

  for (const rawLine of lines) {
    const line = rawLine.replace(/\s+$/, '')
    const trimmed = line.trim()

    if (mode === 'disclaimer') {
      disclaimerBuffer.push(line)
      continue
    }

    if (isDisclaimerLine(trimmed)) {
      flushMeal()
      flushTemplate()
      mode = 'disclaimer'
      disclaimerBuffer.push(line)
      continue
    }

    const sectionMatch = trimmed.match(SECTION_HEADER_RE)
    if (sectionMatch) {
      flushMeal()
      flushTemplate()
      const key = TEMPLATE_SECTION_KEYS[norm(sectionMatch[1])]
      if (key === 'meals') {
        mode = 'meals'
      } else if (key === 'macros') {
        mode = 'top'
      } else if (key) {
        mode = 'template'
        currentTemplateKey = key
        templateBuffer = []
      } else {
        mode = 'top'
      }
      continue
    }

    if (mode === 'meals' || mode === 'recommendations') {
      if (RECOMMENDATIONS_HEADER_RE.test(trimmed)) {
        flushMeal()
        mode = 'recommendations'
        continue
      }

      if (mode === 'meals') {
        const mealMatch = trimmed.match(MEAL_HEADER_RE)
        if (mealMatch) {
          flushMeal()
          currentMeal = {
            emoji: mealMatch[1],
            name: mealMatch[2].trim(),
            hour: mealMatch[3],
            items: [],
            note: ''
          }
          continue
        }
        if (currentMeal) {
          const noteMatch = trimmed.match(NOTE_RE)
          if (noteMatch) {
            currentMeal.note = noteMatch[1].trim()
            continue
          }
          if (isBulletLine(trimmed)) {
            currentMeal.items.push(stripBullet(trimmed))
            continue
          }
          if (trimmed.length > 0 && !MEAL_EMOJI_RE.test(trimmed)) {
            // free text inside a meal block, append to last item or note
            currentMeal.items.push(trimmed)
            continue
          }
        }
      }

      if (mode === 'recommendations') {
        if (isBulletLine(trimmed)) {
          result.recommendations.push(stripBullet(trimmed))
          continue
        }
        if (trimmed.length > 0 && !MEAL_EMOJI_RE.test(trimmed) && !trimmed.startsWith('#')) {
          result.recommendations.push(trimmed)
          continue
        }
      }
      continue
    }

    if (mode === 'template' && currentTemplateKey) {
      templateBuffer.push(line)
      continue
    }
  }

  flushMeal()
  flushTemplate()
  if (disclaimerBuffer.length > 0) {
    result.disclaimer = disclaimerBuffer.join('\n').trim()
  }

  // If we couldn't parse anything meaningful, fall back to raw rendering.
  if (
    result.meals.length === 0 &&
    result.recommendations.length === 0 &&
    !result.sections.generalRules &&
    !result.sections.supplementation &&
    !result.sections.observations &&
    !result.sections.fluids
  ) {
    return { ...result, rawFallback: true }
  }

  return result
}
