// Catálogo de ejercicios del trainer
// Ejecutar seed-exercises.js para cargar en Supabase
// NOTA: Los ejercicios de PECHO tienen only_male: true (no asignar a mujeres)

module.exports = [

  // ─── ESPALDA — VERTICAL (JALONES) ──────────────────────────────────────────
  {
    name: 'Jalón al pecho agarre ancho',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'En polea alta con agarre prono ancho. Tirar la barra hacia el pecho manteniendo el torso ligeramente reclinado. Contraer la espalda en el punto de máxima contracción.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Jalón agarre neutro',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Jalón en polea alta con agarre neutro (palmas enfrentadas). Mayor énfasis en el redondo mayor y dorsal.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Jalón agarre supino',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Jalón en polea alta con agarre supino (palmas hacia ti). Mayor activación del bíceps y dorsal inferior.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Jalón unilateral en polea',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'Jalón a un brazo en polea alta. Permite mayor rango de movimiento y corrección de desequilibrios.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 75,
    is_global: true,
    only_male: false
  },
  {
    name: 'Jalón agarre cerrado',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Jalón en polea alta con agarre estrecho y neutro. Mayor trabajo del dorsal inferior.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },

  // ─── ESPALDA — HORIZONTAL (REMOS) ──────────────────────────────────────────
  {
    name: 'Remo en máquina convergente',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps', 'romboides'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Remo en máquina convergente con pecho apoyado. Tirar los agarres hacia las caderas apretando los omóplatos.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Remo en polea baja agarre V',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Remo sentado en polea baja con accesorio en V. Tirar hacia el abdomen manteniendo la espalda recta.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Remo en polea baja agarre ancho',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps', 'romboides'],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'Remo sentado en polea baja con barra ancha. Mayor énfasis en la parte media de la espalda y romboides.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Remo con mancuerna',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Remo unilateral apoyando la rodilla y mano contraria en un banco. Tirar la mancuerna hacia la cadera.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 75,
    is_global: true,
    only_male: false
  },
  {
    name: 'Remo en barra T (máquina)',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps', 'romboides'],
    equipment: 'máquina',
    difficulty: 'intermedio',
    description: 'Remo en máquina barra T con pecho apoyado. Movimiento bilateral con carga alta, ideal para ganar masa en espalda media.',
    default_sets: 4,
    default_reps: '8-10',
    default_rest_seconds: 120,
    is_global: true,
    only_male: false
  },
  {
    name: 'Remo en banco inclinado con mancuernas',
    category: 'fuerza',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps', 'romboides'],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Tumbado boca abajo en banco inclinado. Remo bilateral con mancuernas, mínimo balance y máxima activación.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },

  // ─── ESPALDA — AISLAMIENTO ──────────────────────────────────────────────────
  {
    name: 'Pullover en polea alta',
    category: 'aislamiento',
    muscle_primary: 'espalda',
    muscle_secondary: ['pecho', 'tríceps'],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'De pie o arrodillado frente a polea alta. Bajar la cuerda en arco hasta las caderas con brazos semirrectos. Aisla el dorsal.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Remo unilateral en polea',
    category: 'aislamiento',
    muscle_primary: 'espalda',
    muscle_secondary: ['bíceps'],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'Remo a un brazo en polea baja o media. Mayor rango de movimiento y control que el remo con mancuerna.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 75,
    is_global: true,
    only_male: false
  },

  // ─── PECHO ──────────────────────────────────────────────────────────────────
  // NOTA: only_male = true — No asignar a mujeres
  {
    name: 'Press en máquina convergente',
    category: 'fuerza',
    muscle_primary: 'pecho',
    muscle_secondary: ['tríceps', 'hombros'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Press de pecho en máquina convergente. Seguro para principiantes, recorrido guiado.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: true
  },
  {
    name: 'Press inclinado con mancuernas',
    category: 'fuerza',
    muscle_primary: 'pecho',
    muscle_secondary: ['tríceps', 'hombros'],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Press en banco inclinado 30-45º con mancuernas. Mayor énfasis en la porción clavicular del pecho.',
    default_sets: 4,
    default_reps: '8-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: true
  },
  {
    name: 'Press plano con mancuernas',
    category: 'fuerza',
    muscle_primary: 'pecho',
    muscle_secondary: ['tríceps', 'hombros'],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Press en banco plano con mancuernas. Mayor rango de movimiento que con barra.',
    default_sets: 4,
    default_reps: '8-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: true
  },
  {
    name: 'Press en multipower plano o inclinado',
    category: 'fuerza',
    muscle_primary: 'pecho',
    muscle_secondary: ['tríceps', 'hombros'],
    equipment: 'multipower',
    difficulty: 'principiante',
    description: 'Press de pecho en Smith Machine plano o inclinado. Recorrido guiado, seguro para cargas altas.',
    default_sets: 4,
    default_reps: '8-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: true
  },
  {
    name: 'Peck deck',
    category: 'aislamiento',
    muscle_primary: 'pecho',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Aperturas en máquina peck deck. Aísla el pecho en contracción máxima. Mantener ligera flexión en codos.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: true
  },
  {
    name: 'Aperturas con mancuernas superior inclinado',
    category: 'aislamiento',
    muscle_primary: 'pecho',
    muscle_secondary: ['hombros'],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Aperturas en banco inclinado 30-45º. Énfasis en pecho superior. Mantener ligera flexión en codos durante todo el movimiento.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: true
  },
  {
    name: 'Fondos en máquina asistida',
    category: 'fuerza',
    muscle_primary: 'pecho',
    muscle_secondary: ['tríceps'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Fondos en máquina asistida inclinando el torso hacia adelante para mayor énfasis en pecho.',
    default_sets: 3,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: true
  },

  // ─── HOMBRO — ANTERIOR ─────────────────────────────────────────────────────
  {
    name: 'Press de hombros en máquina',
    category: 'fuerza',
    muscle_primary: 'hombros',
    muscle_secondary: ['tríceps'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Press de hombros sentado en máquina. Recorrido guiado, ideal para principiantes o como ejercicio de volumen.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Press de hombros con mancuernas',
    category: 'fuerza',
    muscle_primary: 'hombros',
    muscle_secondary: ['tríceps'],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Press de hombros sentado con mancuernas. Mayor estabilización que en máquina. Empujar arriba sin bloquear codos.',
    default_sets: 4,
    default_reps: '8-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Elevaciones frontales con disco',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: [],
    equipment: 'peso_libre',
    difficulty: 'principiante',
    description: 'Elevaciones frontales sujetando un disco con ambas manos. Subir hasta la altura de los hombros con control.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Elevaciones frontales con mancuernas',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: [],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Elevaciones frontales alternadas o simultáneas con mancuernas. Subir a la altura de los hombros.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── HOMBRO — LATERAL ──────────────────────────────────────────────────────
  {
    name: 'Elevaciones laterales con mancuernas',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: [],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Elevaciones laterales de pie o sentado. Subir hasta la altura de los hombros con el codo ligeramente flexionado y las palmas hacia abajo.',
    default_sets: 4,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Elevaciones laterales en máquina',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Elevaciones laterales en máquina. Permite trabajo unilateral y constante tensión en el músculo.',
    default_sets: 4,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Elevaciones laterales con discos',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: [],
    equipment: 'peso_libre',
    difficulty: 'principiante',
    description: 'Elevaciones laterales sujetando discos. Variante económica que mantiene tensión constante.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── HOMBRO — POSTERIOR ────────────────────────────────────────────────────
  {
    name: 'Pájaros con mancuernas',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: ['espalda'],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Apertura posterior con mancuernas inclinado hacia adelante. Trabaja el deltoides posterior y trapecio medio.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Posterior en máquina',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: ['espalda'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Apertura posterior en peck deck o máquina específica. Énfasis en deltoides posterior.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Cruce de poleas posterior',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: ['espalda'],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'Apertura posterior en polea cruzada. Tensión constante en el deltoides posterior durante todo el recorrido.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Face pull',
    category: 'aislamiento',
    muscle_primary: 'hombros',
    muscle_secondary: ['espalda'],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Face pull con cuerda en polea alta. Tirar hacia la cara separando los codos. Trabaja posterior y manguito rotador.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── BÍCEPS ─────────────────────────────────────────────────────────────────
  {
    name: 'Curl en polea baja barra W',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Curl de bíceps en polea baja con barra EZ (W). Tensión constante en todo el recorrido.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl en banco predicador',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Curl de bíceps en banco predicador (Scott). Elimina el balanceo y aísla completamente el bíceps.',
    default_sets: 3,
    default_reps: '10-12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl con mancuernas alterno',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: [],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Curl de bíceps alternado con mancuernas de pie o sentado. Supinar la muñeca al subir.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl en banco inclinado',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: [],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Curl de bíceps en banco inclinado 45º. Estiramiento profundo del bíceps en la posición inicial.',
    default_sets: 3,
    default_reps: '10-12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl martillo',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: ['braquial'],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Curl martillo con agarre neutro. Trabaja el braquial y el braquiorradial además del bíceps.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl en polea baja barra recta',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Curl de bíceps en polea baja con barra recta. Tensión constante, ideal como ejercicio final.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl concentrado araña',
    category: 'aislamiento',
    muscle_primary: 'bíceps',
    muscle_secondary: [],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Curl concentrado o en araña apoyado sobre banco inclinado. Máximo aislamiento del bíceps.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── TRÍCEPS ────────────────────────────────────────────────────────────────
  {
    name: 'Extensiones de tríceps en polea con cuerda',
    category: 'aislamiento',
    muscle_primary: 'tríceps',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Press de tríceps en polea alta con cuerda. Al final del movimiento separar las manos para mayor contracción.',
    default_sets: 4,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Extensiones de tríceps en polea con barra recta',
    category: 'aislamiento',
    muscle_primary: 'tríceps',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Press de tríceps en polea alta con barra recta. Codos pegados al cuerpo durante todo el movimiento.',
    default_sets: 4,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Extensiones de tríceps en polea con barra W',
    category: 'aislamiento',
    muscle_primary: 'tríceps',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Press de tríceps en polea alta con barra EZ. Posición más cómoda para las muñecas.',
    default_sets: 4,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Fondos en máquina asistida para tríceps',
    category: 'fuerza',
    muscle_primary: 'tríceps',
    muscle_secondary: ['pecho'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Fondos en máquina asistida con torso erguido para mayor énfasis en tríceps.',
    default_sets: 3,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Extensión de tríceps sobre la cabeza',
    category: 'aislamiento',
    muscle_primary: 'tríceps',
    muscle_secondary: [],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Extensión de tríceps sobre la cabeza con mancuerna o polea. Trabaja la cabeza larga del tríceps en estiramiento.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Patada de tríceps con polea',
    category: 'aislamiento',
    muscle_primary: 'tríceps',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'Patada de tríceps inclinado en polea baja. Extensión completa del brazo, contracción máxima al final.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Press de tríceps en máquina',
    category: 'fuerza',
    muscle_primary: 'tríceps',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Press de tríceps en máquina específica. Permite cargas altas con recorrido guiado.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },

  // ─── CUÁDRICEPS ─────────────────────────────────────────────────────────────
  {
    name: 'Prensa',
    category: 'fuerza',
    muscle_primary: 'cuádriceps',
    muscle_secondary: ['glúteo', 'femoral'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Prensa de piernas en máquina inclinada. Pies a la anchura de caderas. Bajar hasta 90º de rodilla y empujar sin bloquear.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 120,
    is_global: true,
    only_male: false
  },
  {
    name: 'Hack squat',
    category: 'fuerza',
    muscle_primary: 'cuádriceps',
    muscle_secondary: ['glúteo'],
    equipment: 'máquina',
    difficulty: 'intermedio',
    description: 'Sentadilla hack en máquina. Mayor aislamiento del cuádriceps que la prensa.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 120,
    is_global: true,
    only_male: false
  },
  {
    name: 'Sentadilla en multipower',
    category: 'fuerza',
    muscle_primary: 'cuádriceps',
    muscle_secondary: ['glúteo', 'femoral'],
    equipment: 'multipower',
    difficulty: 'principiante',
    description: 'Sentadilla en Smith Machine. Recorrido guiado, mayor seguridad. Pies ligeramente adelantados.',
    default_sets: 4,
    default_reps: '8-12',
    default_rest_seconds: 120,
    is_global: true,
    only_male: false
  },
  {
    name: 'Extensión de cuádriceps',
    category: 'aislamiento',
    muscle_primary: 'cuádriceps',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Extensión de cuádriceps en máquina. Aislamiento completo del cuádriceps. Subir hasta extensión completa.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Zancadas',
    category: 'fuerza',
    muscle_primary: 'cuádriceps',
    muscle_secondary: ['glúteo', 'femoral'],
    equipment: 'mancuernas',
    difficulty: 'principiante',
    description: 'Zancadas caminando o en sitio con mancuernas. Rodilla trasera casi toca el suelo. Paso largo para activar más el glúteo.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Aductor en máquina',
    category: 'aislamiento',
    muscle_primary: 'cuádriceps',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Aductor de cadera en máquina. Cierre de piernas desde posición abierta. Trabajo interno del muslo.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Abductor en máquina',
    category: 'aislamiento',
    muscle_primary: 'cuádriceps',
    muscle_secondary: ['glúteo'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Abductor de cadera en máquina. Apertura de piernas. Activa el glúteo medio y la fascia.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── FEMORAL / GLÚTEO ───────────────────────────────────────────────────────
  {
    name: 'Curl femoral tumbado',
    category: 'aislamiento',
    muscle_primary: 'femoral',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Curl femoral tumbado boca abajo en máquina. Aislamiento total del bíceps femoral.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 75,
    is_global: true,
    only_male: false
  },
  {
    name: 'Curl femoral sentado',
    category: 'aislamiento',
    muscle_primary: 'femoral',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Curl femoral sentado en máquina. Mayor tensión en el femoral en la posición inicial al estar la cadera flexionada.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 75,
    is_global: true,
    only_male: false
  },
  {
    name: 'Peso muerto rumano',
    category: 'fuerza',
    muscle_primary: 'femoral',
    muscle_secondary: ['glúteo', 'lumbares'],
    equipment: 'barra',
    difficulty: 'intermedio',
    description: 'Peso muerto rumano con barra, mancuernas o en multipower. Bisagra de cadera con rodillas ligeramente flexionadas. Bajar la barra por las piernas hasta sentir el estiramiento del femoral.',
    default_sets: 4,
    default_reps: '8-10',
    default_rest_seconds: 120,
    is_global: true,
    only_male: false
  },
  {
    name: 'Hip thrust',
    category: 'fuerza',
    muscle_primary: 'glúteo',
    muscle_secondary: ['femoral'],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Hip thrust en máquina o con barra en multipower. Empuje de caderas hasta la extensión completa. Mayor activador del glúteo mayor.',
    default_sets: 4,
    default_reps: '10-12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Buenos días en polea baja',
    category: 'fuerza',
    muscle_primary: 'glúteo',
    muscle_secondary: ['lumbares', 'femoral'],
    equipment: 'cable',
    difficulty: 'intermedio',
    description: 'Buenos días con cuerda en polea baja sobre los hombros. Bisagra de cadera con espalda recta.',
    default_sets: 3,
    default_reps: '12',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },
  {
    name: 'Patada de glúteo en polea',
    category: 'aislamiento',
    muscle_primary: 'glúteo',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Patada de glúteo a cuadrupedia o de pie en polea baja. Extensión de cadera manteniendo la espalda neutra.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Sentadilla búlgara',
    category: 'fuerza',
    muscle_primary: 'glúteo',
    muscle_secondary: ['cuádriceps', 'femoral'],
    equipment: 'mancuernas',
    difficulty: 'intermedio',
    description: 'Sentadilla a una pierna con el pie trasero elevado en banco. Paso largo para mayor activación de glúteo.',
    default_sets: 3,
    default_reps: '10',
    default_rest_seconds: 90,
    is_global: true,
    only_male: false
  },

  // ─── GEMELOS ────────────────────────────────────────────────────────────────
  {
    name: 'Gemelo de pie en máquina',
    category: 'fuerza',
    muscle_primary: 'gemelos',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Elevación de talones de pie en máquina o con step. Rango completo: talones abajo, subir en punta de pie. Pausa arriba.',
    default_sets: 4,
    default_reps: '15-20',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Gemelo sentado',
    category: 'fuerza',
    muscle_primary: 'gemelos',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Elevación de talones sentado en máquina. Trabaja el sóleo en mayor medida al estar la rodilla flexionada.',
    default_sets: 4,
    default_reps: '15-20',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Gemelo en prensa',
    category: 'fuerza',
    muscle_primary: 'gemelos',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Elevación de talones en prensa de piernas con la punta de los pies en el borde de la plataforma.',
    default_sets: 3,
    default_reps: '15-20',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── ABDOMEN ────────────────────────────────────────────────────────────────
  {
    name: 'Crunch en polea alta',
    category: 'fuerza',
    muscle_primary: 'abdomen',
    muscle_secondary: [],
    equipment: 'cable',
    difficulty: 'principiante',
    description: 'Crunch arrodillado en polea alta con cuerda. Flexión de columna hacia abajo contrayendo el abdomen.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Elevaciones de piernas',
    category: 'fuerza',
    muscle_primary: 'abdomen',
    muscle_secondary: [],
    equipment: 'peso_corporal',
    difficulty: 'principiante',
    description: 'Elevaciones de piernas colgado en barra o apoyado en paralelas. Subir las piernas hasta 90° o más.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Plancha',
    category: 'fuerza',
    muscle_primary: 'abdomen',
    muscle_secondary: ['lumbares'],
    equipment: 'peso_corporal',
    difficulty: 'principiante',
    description: 'Plancha isométrica en posición de flexión. Mantener el cuerpo alineado sin hundir las caderas.',
    default_sets: 3,
    default_reps: '30s',
    default_rest_seconds: 45,
    is_global: true,
    only_male: false
  },
  {
    name: 'Crunch declinado',
    category: 'fuerza',
    muscle_primary: 'abdomen',
    muscle_secondary: [],
    equipment: 'peso_corporal',
    difficulty: 'principiante',
    description: 'Crunch en banco declinado. Mayor rango de movimiento que el crunch en suelo.',
    default_sets: 3,
    default_reps: '15-20',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },

  // ─── LUMBARES ───────────────────────────────────────────────────────────────
  {
    name: 'Hiperextensiones',
    category: 'fuerza',
    muscle_primary: 'lumbares',
    muscle_secondary: ['glúteo', 'femoral'],
    equipment: 'peso_corporal',
    difficulty: 'principiante',
    description: 'Hiperextensiones en banco romano. Bajar hasta 90° y subir hasta la extensión de cadera. Opcionalmente añadir peso.',
    default_sets: 3,
    default_reps: '15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Extensión lumbar en máquina',
    category: 'fuerza',
    muscle_primary: 'lumbares',
    muscle_secondary: [],
    equipment: 'máquina',
    difficulty: 'principiante',
    description: 'Extensión de lumbares en máquina específica. Movimiento controlado, no hiperextender en el punto final.',
    default_sets: 3,
    default_reps: '12-15',
    default_rest_seconds: 60,
    is_global: true,
    only_male: false
  },
  {
    name: 'Rack pull en multipower',
    category: 'fuerza',
    muscle_primary: 'lumbares',
    muscle_secondary: ['espalda', 'tríceps'],
    equipment: 'multipower',
    difficulty: 'avanzado',
    description: 'Rack pull parcial en Smith Machine desde altura de rodillas. Énfasis en erector espinal y trapecio.',
    default_sets: 4,
    default_reps: '6-8',
    default_rest_seconds: 150,
    is_global: true,
    only_male: false
  }

]
